server:
  port: 8081

kafka:
#  bootstrapAddress: pc01.lan:29092
  producer:
    topic: topic1
  consumer:
    topic: topic1
spring:
  kafka:
    consumer:
      bootstrap-servers: pc01.lan:29092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: pc01.lan:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



